# Generated by Django 5.2.18 on 2026-10-09 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'آیتم غذایی',
                'verbose_name_plural': 'آیتم\u200cهای غذایی',
                'ordering': ['name_fa'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='شروع هفته (شنبه)')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('options', models.ManyToManyField(related_name='menus', to='cafeteria.mealitem', verbose_name='گزینه\u200cهای غذایی')),
            ],
            options={
                'verbose_name': 'منوی روزانه',
                'verbose_name_plural': 'منوی هفتگی',
                'ordering': ['week_start', 'weekday'],
                'unique_together': {('week_start', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_order', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت در زمان سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('is_served', models.BooleanField(default=False, verbose_name='تحویل داده شد')),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('meal_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cafeteria.mealitem', verbose_name='غذا')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cدهنده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cafeteria.weeklymenu', verbose_name='منو')),
            ],
            options={
                'verbose_name': 'سفارش غذا',
                'verbose_name_plural': 'سفارش\u200cهای غذا',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'menu')},
            },
        ),
    ]
