# Generated by Django 5.2.18 on 2026-10-09 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ساختمان')),
                ('section', models.CharField(choices=[('male', 'برادران'), ('female', 'خواهران')], max_length=10, verbose_name='بخش')),
                ('floors', models.PositiveSmallIntegerField(default=4, verbose_name='تعداد طبقات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ساختمان',
                'verbose_name_plural': 'ساختمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج')], max_length=3, verbose_name='نوع')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'تردد',
                'verbose_name_plural': 'تردد\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='شماره اتاق')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='طبقه')),
                ('capacity', models.PositiveSmallIntegerField(default=4, verbose_name='ظرفیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.building', verbose_name='ساختمان')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
                'ordering': ['building', 'floor', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='شماره تخت')),
                ('occupant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed', to=settings.AUTH_USER_MODEL, verbose_name='ساکن')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='dormitory.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'تخت',
                'verbose_name_plural': 'تخت\u200cها',
                'ordering': ['room', 'number'],
                'unique_together': {('room', 'number')},
            },
        ),
    ]
